fix: move `Great Yuan` formation
This commit solves the following error:

```
[jomini_script_system.cpp:262]: Script system
  error!
  Error: create_military_formation effect [ Great
  Yuan does not have state in STATE_GUANGXI ]
  Script location: file: common/history/
  military_formations/
  east_asia_military_formations.txt line: 350
```

This was solved by moving the formation from
`Guangxi` to `Xi'an`.