fix: `JAP` military formation error
This commit solves the following error:

```
[jomini_script_system.cpp:262]: Script system
error!
Error: create_military_formation effect [ Japanese
Shogunate does not have state in
STATE_EASTERN_HUBEI ]
Script location: file: common/history/
military_formations/japan_military_formations.txt
line: 116
```

The fix is simply to delete the formation.