fix: enable private schools for `DLM`
This commit solves the following errors:

```
[jomini_script_system.cpp:262]: Script system
  error!
  Error: set_institution_investment_level effect [
    Attempting to set institution investment level
    for invalid institution type ]
  Script location: file: common/history/countries/
  VEN - Venice.txt line: 116
```

It is not allowed to set the investment level for
an institution that has not been set up.