fix: remove error prone script
This commit fixes the following error:

```
[jomini_script_system.cpp:262]: Script system
error!
Error: c:BRZ trigger [ Failed context switch ]
Script location: file: common/on_actions/
00_code_on_actions.txt line: 2390

[jomini_script_system.cpp:262]: Script system
error!
Error: Event target link 'c' returned an unset
scope
Script location: file: common/on_actions/
00_code_on_actions.txt line: 2390
```

`BRZ` is not a tag that is in use, so it can be
easily removed.