refactor: add vanilla tech tree
# Motivation

To prepare for adding a pre-1836 tech tree, the
technologies that are used implicitly by the mod
should be explicitly added. This will make it
easier to see what changes are added when new
technologies are added.

# Changes

Vanilla technologies in `10_production.txt`,
`20_military.txt` and `30_society.txt` are simply
overwritten. This is to avoid later upstream
changes breaks the mod.

This change also fixes the following error:

```
[jomini_script_system.cpp:262]: Script system
error!
Error: has_journal_entry trigger [ Invalid
database object 'je_risorgimento' ]
Script location: file:
common/technology/technologies/30_society.txt
line: 668
```

# Future work

* Incorporate add new eras (1736-1836)
* Incorporate the existing new technologies
  `track` etc, properly into this new structure